version: '2'
services:
  postgres:
   image: postgres
   hostname: "postgres"
   networks:
     - alantujs
   ports:
     - "5432:5432"

  mongo:
   image: mongo
   hostname: "mongo"
   networks:
     - alantujs
   ports:
     - "27017:27017"

  redis:
   image: redis
   hostname: "redis"
   networks:
     - alantujs
   ports:
     - "6379:6379"          

  alantuback:
   image: alantuback
   hostname: "alantuback"
   networks:
     - alantujs
   ports:
     - "9000:9000"
     - "443:443"
     - "80:80"
   environment:
     - NODE_ENV=production
     - DB_HOST=db
     - MONGO_URL=mongodb://mongo:27017/alantu
     - REDIS_URL=redis
     - REDIS_PORT=6379

networks:
  alantujs:
    # Not using outside this images so far
    external: false